### ISSUE TITLE
Missing start backend

### ISSUE THREAD

**Issue by SonMichael** [bangoc123/protonx-ai-app-UI#1]
Dear Team,

How to start the backend?

<img width="589" alt="Screenshot 2024-05-30 at 05 30 45" src="https://github.com/bangoc123/protonx-ai-app-UI/assets/71422284/db9394dc-e9d6-4672-bded-ba51c450c08a">

**Comment by bangoc123** [comment]
Hi, will update backend project soon.

**Comment by bangoc123** [comment]
@SonMichael Backend here. Check it out! https://github.com/bangoc123/protonx-ai-backend
